### PR TITLE
add metacpan opts

### LINKED ISSUE #5: idea: use MetaCPAN module permission index
Now MetaCPAN has a module permission index.
We could check module permissions via MetaCPAN faster than fetching whole 06perms.txt.
I think it would be nice that Test-PAUSE-Permissions uses MetaCPAN.

The following is a example of querying module permissions to MetaCPAN. 
```
# request
curl https://fastapi.metacpan.org/v1/permission/_search -d '
{
   "query" : {
      "bool" : {
         "should" : [
            { "term" : { "module_name" : "JSON::PP" } },
            { "term" : { "module_name" : "JSON::PP::Boolean" } },
            { "term" : { "module_name" : "JSON::PP::IncrParser" } }
         ]
      }
   },
   "size" : 3
}
'

# response
{
   "_shards" : {
      "total" : 3,
      "successful" : 3,
      "failed" : 0
   },
   "took" : 3,
   "timed_out" : false,
   "hits" : {
      "hits" : [
         {
            "_source" : {
               "module_name" : "JSON::PP",
               "co_maintainers" : [
                  "ISHIGAKI"
               ],
               "owner" : "MAKAMAKA"
            },
            "_type" : "permission",
            "_score" : 3.0540767,
            "_index" : "cpan_v1_01",
            "_id" : "JSON::PP"
         },
         {
            "_source" : {
               "co_maintainers" : [
                  "ISHIGAKI"
               ],
               "owner" : "MAKAMAKA",
               "module_name" : "JSON::PP::Boolean"
            },
            "_type" : "permission",
            "_score" : 3.0540767,
            "_index" : "cpan_v1_01",
            "_id" : "JSON::PP::Boolean"
         },
         {
            "_source" : {
               "owner" : "MAKAMAKA",
               "co_maintainers" : [
                  "ISHIGAKI"
               ],
               "module_name" : "JSON::PP::IncrParser"
            },
            "_type" : "permission",
            "_score" : 2.98695,
            "_id" : "JSON::PP::IncrParser",
            "_index" : "cpan_v1_01"
         }
      ],
      "total" : 3,
      "max_score" : 3.0540767
   }
}
```
cf https://github.com/skaji/App-CPANPermission/blob/master/lib/App/CPANPermission.pm#L47-L65

### PR DESCRIPTION
**Pull request by skaji**
Fix #5 

This PR adds `metacpan => 1` to `all_permissions_ok()`.

If `metacpan => 1`, then Test-PAUSE-Permissions will test permissions
via MetaCPAN API instead of 06perms.txt
using https://metacpan.org/pod/PAUSE::Permissions::MetaCPAN.

### CODE REVIEW

**Comment by skaji** [comment]
This PR purposes to make Test-PAUSE-Permissions fast. So I add output of `prove --timer` on my macOS.

```
❯ prove -l --time xt/10_self.t xt/10_self_metacpan.t
[13:02:13] xt/10_self.t ........... ok     6016 ms ( 0.00 usr  0.00 sys +  2.56 cusr  0.32 csys =  2.88 CPU)
[13:02:19] xt/10_self_metacpan.t .. ok      986 ms ( 0.00 usr  0.00 sys +  0.22 cusr  0.04 csys =  0.26 CPU)
```

**Comment by skaji** [comment]
For concern of Paws which has 9026 packages in it:
PAUSE::Permissions::MetaCPAN will query 1024 packages to MetaCPAN at one time (This 1024 limit comes from elasticsearch).
So it will query to MetaCPAN 9 times for Paws, which will be acceptable by MetaCPAN, I guess.

**Comment by charsbar** [comment]
@skaji Do we require both modules? It would be better, for example, to make ::MetaCPAN recommends/suggests and warn/die/skip the test if it is not installed when _ok is called with ```metacpan => 1``` option.

It might also help to accept some environmental variable, so that you don't need to fix all the permission tests you have :)

**Comment by skaji** [comment]
@charsbar Thanks for your review.

I switched "requires" to "recommends". On runtime, if `metacpan => 1` but PAUSE::Permissions::MetaCPAN is not installed, then simply call `die()`.
Here I think `die()` is preferred because Test-PAUSE-Permissions is for module authors, not for end-users.

I also added environment variable TEST_PAUSE_PERMISSIONS_METACPAN to use MetaCPAN API.

**Comment by charsbar** [comment]
Thanks!

**Comment by skaji** [comment]
I will release this as 0.07 to CPAN today.

**Pull request merged**
